version: '3.8'

services:
  
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASS}   
      POSTGRES_DB: ${DB_NAME}         
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "5432:5432" 

  # Serviço da API Node.js
  api:
    build: .
    restart: always
    ports:
      - "3001:3001" 
    depends_on:
      - db 
    environment:
      DB_HOST: db       
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      API_PORT: 3001
    volumes:
      - ./src:/app/src  
    command: npm run dev 
volumes:
  postgres_data:

